# Generated by Django 4.0.5 on 2022-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_supir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supir',
            name='tgl_lahir',
            field=models.DateField(null=True),
        ),
    ]
