# Generated by Django 4.0.5 on 2022-10-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_supir_tgl_lahir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supir',
        ),
    ]
