# Generated by Django 4.0.5 on 2022-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_delete_supir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('jadwal', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='supir_img')),
            ],
        ),
    ]
