# Generated by Django 4.0.5 on 2022-10-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_supir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Angkutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_angkutan', models.CharField(max_length=4)),
                ('rute', models.CharField(max_length=200)),
                ('nama_supir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.supir')),
            ],
        ),
    ]
