# Generated by Django 4.0.5 on 2022-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_jenis_angkutan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_angkutan',
            name='no_angkutan',
            field=models.CharField(max_length=10),
        ),
    ]
