# Generated by Django 4.0.5 on 2022-10-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_jenis_angkutan_no_angkutan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenis_angkutan',
            name='nama_supir',
        ),
        migrations.CreateModel(
            name='Laporan_Narik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_sebelum', models.PositiveIntegerField()),
                ('km_sesudah', models.PositiveIntegerField(null=True)),
                ('bbm', models.PositiveIntegerField()),
                ('setoran', models.PositiveIntegerField(null=True)),
                ('nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.supir')),
                ('no_angkutan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.jenis_angkutan')),
            ],
        ),
    ]
