# Generated by Django 4.0.5 on 2022-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_remove_jenis_angkutan_nama_supir_laporan_narik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan_narik',
            name='bbm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laporan_narik',
            name='km_sebelum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laporan_narik',
            name='km_sesudah',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laporan_narik',
            name='setoran',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
