# Generated by Django 4.0.5 on 2022-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_laporan_narik_bbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan_narik',
            name='tgl',
            field=models.DateTimeField(null=True),
        ),
    ]
